import { StyleSheet } from "react-native";

import { color, font, tabularNums } from "@/components/jua-kali/theme";

export const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: color.stone },
    content: { gap: 14, paddingTop: 8 },
    hero: { flexDirection: "row", alignItems: "center", gap: 14, paddingVertical: 6 },
    heroBody: { flex: 1, gap: 2 },
    title: {
        fontFamily: font.displayMedium,
        fontSize: 24,
        fontWeight: "600",
        letterSpacing: -0.5,
        color: color.charcoal,
    },
    sub: { fontFamily: font.body, fontSize: 12, color: color.mist },
    cardTitle: {
        fontFamily: font.displayMedium,
        fontSize: 18,
        fontWeight: "600",
        color: color.charcoal,
        flexShrink: 1,
    },
    titleRow: { flexDirection: "row", alignItems: "center", gap: 7 },
    body: { fontFamily: font.body, fontSize: 13, lineHeight: 19, color: color.ink },
    hint: { fontFamily: font.body, fontSize: 12, lineHeight: 17, color: color.mist },
    status: { fontFamily: font.body, fontSize: 12, color: color.brassDeep, textAlign: "center" },
    kpiRow: { flexDirection: "row", alignItems: "center", gap: 16 },
    kpiBlock: { gap: 2, flex: 1 },
    kpiValue: {
        fontFamily: font.display,
        fontSize: 30,
        fontWeight: "700",
        letterSpacing: -0.8,
        color: color.charcoal,
        fontVariant: tabularNums,
    },
    kpiLabel: {
        fontFamily: font.bodyBold,
        fontSize: 10,
        fontWeight: "700",
        letterSpacing: 0.6,
        textTransform: "uppercase",
        color: color.mist,
    },
    kpiDivider: { width: 1, alignSelf: "stretch", backgroundColor: color.line },
    progressTrack: { height: 3, borderRadius: 2, backgroundColor: "rgba(20,24,22,0.08)", overflow: "hidden" },
    progressFill: { height: "100%", backgroundColor: color.brass },
    tagRow: { gap: 6, paddingVertical: 2 },
    composerRow: { flexDirection: "row", gap: 8, alignItems: "flex-end" },
    composerInput: {
        flex: 1,
        minHeight: 72,
        maxHeight: 140,
        borderWidth: 1,
        borderColor: color.lineStrong,
        borderRadius: 4,
        paddingHorizontal: 12,
        paddingVertical: 10,
        color: color.ink,
        backgroundColor: color.paper,
        fontFamily: font.body,
        fontSize: 14,
        textAlignVertical: "top",
    },
    micButton: {
        width: 44,
        height: 44,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: color.brass,
        backgroundColor: color.paper,
        alignItems: "center",
        justifyContent: "center",
    },
    micListening: { backgroundColor: color.brass },
    listening: { fontFamily: font.bodyBold, fontSize: 11, fontWeight: "700", color: color.brassDeep },
    kpiInputRow: { flexDirection: "row", gap: 8, alignItems: "center" },
    kpiInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: color.lineStrong,
        borderRadius: 4,
        paddingHorizontal: 12,
        paddingVertical: 11,
        color: color.ink,
        backgroundColor: color.paper,
        fontFamily: font.body,
        fontSize: 15,
    },
    selfLink: {
        fontFamily: font.bodyBold,
        fontSize: 12,
        fontWeight: "700",
        color: color.brassDeep,
        textAlign: "center",
        paddingVertical: 4,
    },
    wisdomStack: { gap: 12 },
    checkInRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 4 },
    checkInValue: {
        fontFamily: font.bodyBold,
        fontSize: 13,
        fontWeight: "700",
        color: color.charcoal,
        minWidth: 36,
        fontVariant: tabularNums,
    },
    checkInNote: { flex: 1, fontFamily: font.body, fontSize: 12, color: color.ink },
    checkInWhen: { fontFamily: font.body, fontSize: 11, color: color.mist },
    digestRow: { gap: 2, paddingVertical: 4 },
    proofBtn: { alignSelf: "center" },
    proofHint: { fontFamily: font.body, fontSize: 11, color: color.mist, textAlign: "center" },
});
