import { StyleSheet } from "react-native";

import { color, elevation, font, tabularNums } from "@/components/jua-kali/theme";

export const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: color.stone },
    loadingScreen: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: color.stone },
    content: { gap: 14, paddingTop: 8 },
    hero: { gap: 10 },
    heroRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    brand: {
        fontFamily: font.display,
        fontSize: 28,
        fontWeight: "700",
        letterSpacing: -1,
        color: color.charcoal,
    },
    heroTitle: {
        fontFamily: font.displayMedium,
        fontSize: 22,
        fontWeight: "600",
        letterSpacing: -0.4,
        color: color.charcoal,
    },
    bridge: {
        fontFamily: font.body,
        fontSize: 12,
        lineHeight: 17,
        color: color.mist,
    },
    fieldHint: {
        fontFamily: font.body,
        fontSize: 12,
        lineHeight: 17,
        color: color.mist,
    },
    inlineLink: {
        fontFamily: font.bodyBold,
        fontSize: 12,
        fontWeight: "700",
        color: color.brassDeep,
        textAlign: "center",
        paddingVertical: 4,
    },
    dueRow: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 1 },
    titleWithHint: { flexDirection: "row", alignItems: "center", gap: 6, flex: 1 },
    insightHead: { flexDirection: "row", alignItems: "center", gap: 6 },
    metricLabelRow: { flexDirection: "row", alignItems: "center", gap: 3 },
    gateEyebrow: {
        fontFamily: font.bodyBold,
        fontSize: 10,
        fontWeight: "700",
        letterSpacing: 0.6,
        textTransform: "uppercase",
        color: color.brassDeep,
    },
    heroActions: { flexDirection: "row", gap: 8, justifyContent: "center" },
    emptyBtn: { width: 260 },
    status: { fontFamily: font.body, fontSize: 12, color: color.brassDeep, textAlign: "center" },
    cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
    cardTitle: {
        fontFamily: font.displayMedium,
        fontSize: 20,
        fontWeight: "600",
        color: color.charcoal,
        flex: 1,
    },
    meta: { fontFamily: font.bodyBold, fontSize: 11, fontWeight: "700", color: color.brass },
    metaDanger: { color: color.danger },
    // Brass is the trust/permission color — the approve Button variant is the
    // only place it appears as a fill.
    consequence: {
        gap: 3,
        padding: 10,
        borderRadius: 4,
        backgroundColor: color.stone,
        borderWidth: 1,
        borderColor: color.line,
    },
    consequenceLabel: {
        fontFamily: font.bodyBold,
        fontSize: 9,
        fontWeight: "700",
        letterSpacing: 0.8,
        textTransform: "uppercase",
        color: color.mist,
        marginBottom: 2,
    },
    consequenceLine: { fontFamily: font.body, fontSize: 12, lineHeight: 17, color: color.ink },
    chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
    emptyCard: { alignItems: "center", gap: 14, paddingVertical: 28 },
    emptyGlyph: { width: 72, height: 72, alignItems: "center", justifyContent: "center" },
    emptyRing: {
        position: "absolute",
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 1.5,
        borderColor: color.brass,
        opacity: 0.5,
    },
    emptyRingInner: { width: 40, height: 40, borderRadius: 20, opacity: 0.9 },
    emptyTitle: {
        fontFamily: font.displayMedium,
        fontSize: 18,
        fontWeight: "600",
        color: color.charcoal,
    },
    strip: { gap: 8, paddingVertical: 2 },
    stripItem: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 4,
        backgroundColor: color.paper,
        borderWidth: 1,
        borderColor: color.line,
        minWidth: 120,
        gap: 2,
    },
    stripItemOn: { borderColor: color.brass, backgroundColor: color.brassSoft },
    stripName: { fontFamily: font.bodyBold, fontSize: 12, fontWeight: "700", color: color.ink },
    stripNameOn: { color: color.charcoal },
    stripAmt: { fontFamily: font.body, fontSize: 11, color: color.brass, fontVariant: tabularNums },
    stack: { gap: 12 },
    metrics: { flexDirection: "row", gap: 8 },
    metric: { flex: 1, padding: 10, borderRadius: 4, backgroundColor: color.stone, gap: 2 },
    metricValue: {
        fontFamily: font.display,
        fontSize: 22,
        fontWeight: "700",
        color: color.charcoal,
        letterSpacing: -0.4,
        fontVariant: tabularNums,
    },
    metricLabel: {
        fontFamily: font.bodyBold,
        fontSize: 9,
        fontWeight: "700",
        color: color.mist,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    progressTrack: {
        height: 3,
        borderRadius: 2,
        backgroundColor: "rgba(20,24,22,0.08)",
        overflow: "hidden",
    },
    progressFill: { height: "100%", backgroundColor: color.brass },
    // Presence line
    presence: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        flexWrap: "wrap",
    },
    presenceText: {
        fontFamily: font.body,
        fontSize: 12,
        color: color.mist,
        flexShrink: 1,
    },
    presenceBadge: {
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: 4,
        backgroundColor: color.brassSoft,
        borderWidth: 1,
        borderColor: "rgba(166,124,45,0.25)",
    },
    presenceBadgeText: {
        fontFamily: font.bodyBold,
        fontSize: 10,
        fontWeight: "700",
        letterSpacing: 0.4,
        textTransform: "uppercase",
        color: color.brassDeep,
    },
    // Arrival moment — a trust card laid out as a voice line.
    arrival: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 10,
        padding: 14,
    },
    arrivalBody: { flex: 1, gap: 2 },
    arrivalVoice: {
        fontFamily: font.bodyMedium,
        fontSize: 14,
        lineHeight: 20,
        color: color.ink,
    },
    arrivalWhen: {
        fontFamily: font.body,
        fontSize: 11,
        color: color.mist,
    },
    // Proposal card
    proposal: { gap: 10 },
    proposalBody: {
        fontFamily: font.body,
        fontSize: 14,
        lineHeight: 20,
        color: color.ink,
    },
    // Scorecard commentary
    commentary: {
        fontFamily: font.body,
        fontSize: 12,
        color: color.brassDeep,
        marginTop: 4,
    },
    shareRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 8,
    },
    shareRowInner: { flexDirection: "row", alignItems: "center", gap: 5 },
    shareLink: {
        fontFamily: font.bodyBold,
        fontSize: 12,
        fontWeight: "700",
        color: color.brassDeep,
    },
    sparkTrack: { height: 34, justifyContent: "center" },
    insight: {
        gap: 4,
        padding: 12,
        borderRadius: 4,
        backgroundColor: color.brassSoft,
        borderWidth: 1,
        borderColor: "rgba(166,124,45,0.25)",
    },
    insightLabel: {
        fontFamily: font.bodyBold,
        fontSize: 10,
        fontWeight: "700",
        color: color.brassDeep,
        letterSpacing: 0.6,
        textTransform: "uppercase",
    },
    insightBody: { fontFamily: font.body, fontSize: 13, lineHeight: 18, color: color.ink },
    shimmerTrack: {
        height: 2,
        borderRadius: 99,
        overflow: "hidden",
        backgroundColor: "rgba(166,124,45,0.12)",
    },
    shimmerBar: { width: "40%", height: "100%", backgroundColor: color.brass, borderRadius: 99 },
    toolRow: { gap: 6 },
    toolRowLarge: { gap: 8 },
    toolChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 4,
        backgroundColor: color.stone,
    },
    toolChipLarge: {
        gap: 10,
        paddingHorizontal: 14,
        paddingVertical: 13,
        minHeight: 48,
        backgroundColor: color.paper,
        borderWidth: 1,
        borderColor: color.line,
    },
    toolChipRun: { backgroundColor: color.brassSoft },
    toolChipFail: { backgroundColor: "rgba(139,58,47,0.08)" },
    toolDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: color.lineStrong },
    toolDotLarge: { width: 10, height: 10 },
    toolName: { fontFamily: font.bodyBold, fontSize: 11, fontWeight: "700", color: color.charcoal, flexShrink: 1 },
    toolNameLarge: { fontSize: 13 },
    // The ceremony — the ritual card taken over by a run in flight.
    ceremonyCard: {
        paddingTop: 22,
        paddingBottom: 18,
        ...elevation.raised,
    },
    ceremonyHead: { alignItems: "center", gap: 6 },
    ceremonyTitle: {
        fontFamily: font.displayMedium,
        fontSize: 21,
        fontWeight: "600",
        letterSpacing: -0.4,
        color: color.charcoal,
        textAlign: "center",
    },
    promptRow: { gap: 6, paddingVertical: 2 },
    runDone: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 8,
        paddingHorizontal: 2,
        paddingTop: 2,
    },
    runDoneText: { fontFamily: font.body, fontSize: 12, lineHeight: 17, color: color.ink, flex: 1 },
    runDoneLink: { fontFamily: font.bodyBold, fontSize: 12, fontWeight: "700", color: color.brassDeep },
    runError: { fontFamily: font.body, fontSize: 12, color: color.danger },
    // Digest artifact card
    digestTitle: {
        fontFamily: font.displayMedium,
        fontSize: 18,
        fontWeight: "600",
        color: color.charcoal,
        flex: 1,
    },
    digestWhen: { fontFamily: font.bodyBold, fontSize: 11, fontWeight: "700", color: color.mist },
    digestSummary: { fontFamily: font.body, fontSize: 14, lineHeight: 21, color: color.ink },
    digestRule: { height: 1, backgroundColor: color.line },
    digestSection: { gap: 3 },
    digestSectionLabel: {
        fontFamily: font.bodyBold,
        fontSize: 9,
        fontWeight: "700",
        letterSpacing: 0.8,
        textTransform: "uppercase",
        color: color.brassDeep,
    },
    digestSectionBody: { fontFamily: font.body, fontSize: 13, lineHeight: 19, color: color.ink },
    digestFoot: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 8,
    },
    digestEvidenceRow: { flexDirection: "row", alignItems: "center", gap: 6, flexWrap: "wrap", flex: 1 },
    digestEvidenceLabel: {
        fontFamily: font.bodyBold,
        fontSize: 9,
        fontWeight: "700",
        letterSpacing: 0.8,
        textTransform: "uppercase",
        color: color.mist,
    },
    evidenceChip: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        backgroundColor: color.brassSoft,
        borderWidth: 1,
        borderColor: "rgba(166,124,45,0.25)",
    },
    evidenceChipText: {
        fontFamily: font.bodyBold,
        fontSize: 10,
        fontWeight: "700",
        letterSpacing: 0.4,
        textTransform: "uppercase",
        color: color.brassDeep,
    },
    // The digest seal — the artifact's signature line.
    sealRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        justifyContent: "center",
        paddingTop: 2,
    },
    sealText: {
        fontFamily: font.bodyMedium,
        fontSize: 10,
        letterSpacing: 0.5,
        textTransform: "uppercase",
        color: color.mist,
    },
    gate: { gap: 10 },
    gateBody: { fontFamily: font.body, fontSize: 14, lineHeight: 20, color: color.ink },
    discard: {
        fontFamily: font.bodyBold,
        fontSize: 13,
        fontWeight: "700",
        color: color.mist,
        textAlign: "center",
        paddingVertical: 8,
    },
    composer: { gap: 10 },
    emailAlt: {
        fontFamily: font.body,
        fontSize: 11,
        lineHeight: 16,
        color: color.mist,
    },
    composerInput: {
        minHeight: 64,
        maxHeight: 100,
        borderWidth: 1,
        borderColor: color.lineStrong,
        borderRadius: 4,
        paddingHorizontal: 12,
        paddingVertical: 10,
        color: color.ink,
        backgroundColor: color.stone,
        fontFamily: font.body,
        fontSize: 14,
        textAlignVertical: "top",
    },
    threadToggle: { fontFamily: font.bodyBold, fontSize: 12, fontWeight: "700", color: color.brass },
    bubble: { gap: 2, padding: 10, borderRadius: 4, backgroundColor: color.stone },
    bubbleMeta: { fontFamily: font.bodyBold, fontSize: 10, fontWeight: "700", color: color.mist },
    bubbleBody: { fontFamily: font.body, fontSize: 12, lineHeight: 17, color: color.ink },
});
