import { Platform, StyleSheet } from "react-native";

import { color, font, layout } from "@/components/jua-kali/theme";

export const styles = StyleSheet.create({
    hintBtn: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 1,
        borderColor: color.lineStrong,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: color.paper,
    },
    hintMark: {
        fontFamily: font.bodyBold,
        fontSize: 10,
        fontWeight: "700",
        color: color.mist,
        lineHeight: 12,
    },
    labelRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    labelText: {
        fontFamily: font.bodyBold,
        fontSize: 9,
        fontWeight: "700",
        color: color.mist,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    tipBackdrop: {
        flex: 1,
        backgroundColor: "rgba(20,24,22,0.45)",
        justifyContent: "center",
        padding: 24,
    },
    tipCard: {
        backgroundColor: color.paper,
        borderRadius: 8,
        padding: 18,
        gap: 10,
        borderWidth: 1,
        borderColor: color.line,
        maxWidth: 400,
        alignSelf: "center",
        width: "100%",
    },
    tipTitle: {
        fontFamily: font.displayMedium,
        fontSize: 18,
        fontWeight: "600",
        color: color.charcoal,
    },
    tipBody: { fontFamily: font.body, fontSize: 14, lineHeight: 20, color: color.ink },
    tipClose: {
        alignSelf: "flex-start",
        marginTop: 4,
        backgroundColor: color.charcoal,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 4,
    },
    tipCloseText: { fontFamily: font.bodyBold, color: color.paper, fontWeight: "700", fontSize: 13 },
    coach: {
        gap: 12,
        padding: 14,
        backgroundColor: color.paper,
        borderWidth: 1,
        borderColor: color.brass,
        borderRadius: 6,
    },
    coachHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
    coachActions: { flexDirection: "row", alignItems: "center", gap: 14 },
    coachSummary: {
        fontFamily: font.bodyMedium,
        fontSize: 13,
        color: color.ink,
        marginTop: 2,
    },
    coachEyebrow: {
        fontFamily: font.bodyBold,
        fontSize: 11,
        fontWeight: "700",
        letterSpacing: 1.2,
        textTransform: "uppercase",
        color: color.brassDeep,
    },
    coachDismiss: { fontFamily: font.bodyBold, fontSize: 12, fontWeight: "700", color: color.mist },
    coachSteps: { gap: 10 },
    coachStep: { flexDirection: "row", gap: 10, alignItems: "flex-start" },
    coachN: {
        fontFamily: font.display,
        fontSize: 16,
        fontWeight: "700",
        color: color.brassDeep,
        width: 18,
    },
    coachCopy: { flex: 1, gap: 2 },
    coachTitle: { fontFamily: font.bodyBold, fontSize: 13, fontWeight: "700", color: color.charcoal },
    coachBody: { fontFamily: font.body, fontSize: 12, lineHeight: 17, color: color.mist },
    coachLink: {
        fontFamily: font.bodyBold,
        fontSize: 12,
        fontWeight: "700",
        color: color.brassDeep,
        paddingTop: 2,
    },
    welcome: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        marginHorizontal: 14,
        marginBottom: 6,
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: color.paper,
        borderWidth: 1,
        borderColor: color.line,
        borderRadius: 6,
        maxWidth: layout.maxWidth,
        // Centered under the same gutter as the page frame — on wide screens a
        // stretched banner would otherwise hug the left edge of the viewport.
        width: "100%",
        alignSelf: "center",
    },
    welcomeLead: {
        flex: 1,
        fontFamily: font.bodyMedium,
        fontSize: 12,
        lineHeight: 16,
        color: color.ink,
    },
    welcomeActions: { flexDirection: "row", alignItems: "center", gap: 12 },
    sheetRoot: { flex: 1, justifyContent: "flex-end", alignItems: "center" },
    sheetDim: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(20,24,22,0.4)" },
    sheet: {
        width: "100%",
        backgroundColor: color.paper,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        paddingHorizontal: 16,
        paddingTop: 8,
        borderWidth: 1,
        borderColor: color.line,
        gap: 8,
    },
    sheetHandle: {
        alignSelf: "center",
        width: 36,
        height: 4,
        borderRadius: 2,
        backgroundColor: color.lineStrong,
        marginBottom: 4,
    },
    sheetHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
    sheetTitle: {
        fontFamily: font.displayMedium,
        fontSize: 22,
        fontWeight: "600",
        color: color.charcoal,
    },
    sheetSub: { fontFamily: font.body, fontSize: 12, color: color.mist, marginBottom: 4 },
    sheetList: { gap: 10, paddingBottom: 12 },
    termCard: {
        gap: 4,
        padding: 12,
        borderRadius: 6,
        backgroundColor: color.stone,
        borderWidth: 1,
        borderColor: color.line,
    },
    termCardOn: { borderColor: color.brass, backgroundColor: color.brassSoft },
    termLabel: { fontFamily: font.bodyBold, fontSize: 14, fontWeight: "700", color: color.charcoal },
    termShort: { fontFamily: font.bodyMedium, fontSize: 12, color: color.brass },
    termBody: { fontFamily: font.body, fontSize: 13, lineHeight: 18, color: color.ink },
    helpBtn: {
        borderWidth: 1,
        borderColor: color.lineStrong,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 4,
        backgroundColor: color.paper,
        minHeight: 36,
        justifyContent: "center",
    },
    helpBtnText: { fontFamily: font.bodyBold, fontSize: 12, fontWeight: "700", color: color.charcoal },
    helpMenu: {
        position: "absolute",
        top: 40,
        right: 0,
        zIndex: 20,
        minWidth: 160,
        backgroundColor: color.paper,
        borderWidth: 1,
        borderColor: color.lineStrong,
        borderRadius: 6,
        overflow: "hidden",
        ...Platform.select({
            web: { boxShadow: "0 8px 24px rgba(20,24,22,0.12)" } as object,
            default: {
                shadowColor: color.charcoal,
                shadowOpacity: 0.12,
                shadowRadius: 12,
                shadowOffset: { width: 0, height: 6 },
                elevation: 4,
            },
        }),
    },
    helpItem: { paddingHorizontal: 14, paddingVertical: 12 },
    helpItemText: { fontFamily: font.bodyBold, fontSize: 13, fontWeight: "700", color: color.charcoal },
    helpFooter: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: color.line,
        marginTop: 2,
    },
});
